version: 1
labels:
- label: "type/feature"
  title: "^feat*"
- label: "type/fix"
  title: "^fix*"
- label: "type/docs"
  title: "^docs*"
- label: "type/style"
  title: "^style*"
- label: "type/refactor"
  title: "^refactor*"
- label: "type/test"
  title: "^test*"
- label: "type/chore"
  title: "^chore*"
- label: "type/revert"
  title: "^revert*"
- label: "component/ci"
  title: "^ci*"
- label: "component/ci"
  title: "*(ci):*"
- label: "component/test"
  title: "^test*"
- label: "component/test"
  title: "*(test):*"
- label: "component/doc"
  title: "^doc*"
- label: "component/doc"
  title: "*(doc):*"
- label: "component/datafeed"
  title: "^datafeed*"
- label: "component/datafeed"
  title: "*(datafeed):*"
- label: "component/order"
  title: "^order*"
- label: "component/order"
  title: "*(order):*"
- label: "component/executor"
  title: "^executor*"
- label: "component/executor"
  title: "*(executor):*"
- label: "component/filter"
  title: "^filter*"
- label: "component/filter"
  title: "*(filter):*"
