name: Label PRs

on:
- workflow_call

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: srvaroa/labeler@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        config_path: "EdaoQuant/common-workflows/.github/issue-labeler.yml"
